use_frameworks!

platform :ios, '13.0'

target 'CoreDataDitto_Example' do
  pod 'CoreDataDitto', :path => '../'

  target 'CoreDataDitto_Tests' do
    inherit! :search_paths

    pod "Fakery"
    
  end
end
